//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitaplar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kitaplar()
        {
            this.OduncIslemleri = new HashSet<OduncIslemleri>();
            this.Kategoriler = new HashSet<Kategoriler>();
            this.Yazarlar = new HashSet<Yazarlar>();
            this.OduncTalepleri = new HashSet<OduncTalepleri>();
        }
    
        public int KitapID { get; set; }
        public string KitapAdi { get; set; }
        public string ISBN { get; set; }
        public Nullable<int> YayineviID { get; set; }
        public Nullable<int> BasimYili { get; set; }
        public Nullable<int> Stok { get; set; }
        public Nullable<int> SayfaSayisi { get; set; }
    
        public virtual Yayinevleri Yayinevleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OduncIslemleri> OduncIslemleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kategoriler> Kategoriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yazarlar> Yazarlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OduncTalepleri> OduncTalepleri { get; set; }
    }
}
