//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class OduncTalepleri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OduncTalepleri()
        {
            this.OduncIslemleri = new HashSet<OduncIslemleri>();
        }
    
        public int TalepID { get; set; }
        public int UyeID { get; set; }
        public int KitapID { get; set; }
        public System.DateTime TalepTarihi { get; set; }
        public string TalepDurumu { get; set; }
        public Nullable<int> OnaylayanID { get; set; }
        public Nullable<System.DateTime> OnayTarihi { get; set; }
        public string Aciklama { get; set; }
    
        public virtual Kitaplar Kitaplar { get; set; }
        public virtual Kullanicilar Onaylayan { get; set; }
        public virtual Kullanicilar Uye { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OduncIslemleri> OduncIslemleri { get; set; }
    }
}
