//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class OduncIslemleri
    {
        public int IslemID { get; set; }
        public Nullable<int> KitapID { get; set; }
        public Nullable<int> KullaniciID { get; set; }
        public Nullable<System.DateTime> VerilisTarihi { get; set; }
        public Nullable<System.DateTime> TeslimTarihi { get; set; }
        public Nullable<System.DateTime> IadeTarihi { get; set; }
        public Nullable<int> GecikmeGun { get; set; }
        public Nullable<decimal> CezaTutari { get; set; }
        public Nullable<int> IslemYapanID { get; set; }
        public bool CezaOdendi { get; set; }
        public Nullable<int> TalepID { get; set; }
        public bool UzatmaTalepEdildi { get; set; }
        public Nullable<System.DateTime> UzatmaTarihi { get; set; }
        public Nullable<bool> UzatmaReddedildi { get; set; }
        public string UzatmaReddetmeNedeni { get; set; }
    
        public virtual Kitaplar Kitaplar { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual Kullanicilar Kullanicilar1 { get; set; }
        public virtual OduncTalepleri OduncTalepleri { get; set; }
    }
}
