//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Raporlar
    {
        public int RaporID { get; set; }
        public Nullable<int> KullaniciID { get; set; }
        public string IslemTipi { get; set; }
        public string IslemAciklamasi { get; set; }
        public Nullable<System.DateTime> IslemTarihi { get; set; }
        public Nullable<int> IlgiliKitapID { get; set; }
        public Nullable<int> IlgiliUyeID { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
