//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class UyeDetay
    {
        public int UyeDetayID { get; set; }
        public int KullaniciID { get; set; }
        public string Adres { get; set; }
        public Nullable<decimal> Bakiye { get; set; }
        public string Statu { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
